# dbal types changed fo compatibility with Postgres DateTime
doctrine:
    dbal:
        url: '%env(resolve:DATABASE_URL)%'
        types:
            datetime: Doctrine\DBAL\Types\VarDateTimeType
            datetimetz: Doctrine\DBAL\Types\VarDateTimeType
            time: Doctrine\DBAL\Types\VarDateTimeType
            datetime_immutable: Doctrine\DBAL\Types\VarDateTimeImmutableType
            datetimetz_immutable: Doctrine\DBAL\Types\VarDateTimeImmutableType
            time_immutable: Doctrine\DBAL\Types\VarDateTimeImmutableType

        # IMPORTANT: You MUST configure your server version,
        # either here or in the DATABASE_URL env var (see .env file)
        #server_version: '13'
    orm:
        auto_generate_proxy_classes: true
        naming_strategy: doctrine.orm.naming_strategy.underscore_number_aware
        auto_mapping: true
        mappings:
            App:
                is_bundle: false
                type: annotation
                dir: '%kernel.project_dir%/src/Entity'
                prefix: 'App\Entity'
                alias: App
        dql:
            string_functions:
                JSON_GET: Scienta\DoctrineJsonFunctions\Query\AST\Functions\Postgresql\JsonGet
                JSON_GET_TEXT: Scienta\DoctrineJsonFunctions\Query\AST\Functions\Postgresql\JsonGetText
                JSON_GET_PATH: Scienta\DoctrineJsonFunctions\Query\AST\Functions\Postgresql\JsonGetPath
                JSON_GET_PATH_TEXT: Scienta\DoctrineJsonFunctions\Query\AST\Functions\Postgresql\JsonGetPathText
